name: Mr.Chang
url: https://ibitbe.com
description: Mr.Chang's blog

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
