name: iBitBe
url: https://ibitbe.com
description: 欢迎来到我的博客！

permalink: /:year/:month/:day/:title/
paginate: 6

gems: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM 
excerpt_separator:  '<!-- more -->'
